layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - nathan-fiscaletti.github.io

  social_media:
    linkedin: nathan-fiscaletti
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: nathan-fiscaletti
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: PHP
    web_url: https://github.com/topics/php
    image_url: https://github.com/github/explore/blob/master/topics/php/php.png?raw=true

  - name: iOS
    web_url: https://github.com/topics/ios
    image_url: https://github.com/github/explore/blob/master/topics/ios/ios.png?raw=true

  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://github.com/github/explore/blob/master/topics/android/android.png?raw=true
