layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 1000
  exclude:
    archived: false
    forks: true
    projects:
      - project-downloads
      - sf-rlteams

social_media:
  website: https://nathanf.tk/
  linkedin: nathan-fiscaletti
  facebook: nathan-fiscaletti
  stackoverflow: 1720829
  medium: fisc510
  # behance: your_username
  # dribbble: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: PHP
    web_url: https://github.com/topics/php
    image_url: https://github.com/github/explore/blob/master/topics/php/php.png?raw=true

  - name: iOS
    web_url: https://github.com/topics/ios
    image_url: https://github.com/github/explore/blob/master/topics/ios/ios.png?raw=true

  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://github.com/github/explore/blob/master/topics/android/android.png?raw=true
